package com.dartmedia.brandedsdk.service

enum class MainServiceActionsEnum {
    START_SERVICE,SETUP_VIEWS,END_CALL,SWITCH_CAMERA,TOGGLE_AUDIO,TOGGLE_VIDEO,TOGGLE_AUDIO_DEVICE,
    TOGGLE_SCREEN_SHARE,STOP_SERVICE
}